# Copyright (c) 2019, Pete Batard <pete@akeo.ie>
# SPDX-License-Identifier: BSD-3-Clause

image: Ubuntu1804

skip_commits:
  files:
    - '**/*.md'
    - '**/*.txt'

environment:
  FIRMWARE_VERSION: 1.0.0

install:
  - sh: sudo apt-get update -qq
  - sh: sudo -E apt-get install -y gcc-aarch64-linux-gnu python3-distutils
  - sh: git submodule update --init --recursive

build_script:
  - sh: ./build_firmware.sh

after_build:
  - sh: sha256sum Build/RPi3/RELEASE_GCC5/FV/RPI_EFI.fd

artifacts:
  - path: Build/RPi3/RELEASE_GCC5/FV/RPI_EFI.fd
    name: RPi3 UEFI Firmware Image
    type: file
